#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compresses archive of it

mysqldump -u root --password="$1" --all-databases > backup.sql

# Compressing the dump
tar -czf "$(date +%d-%m-%Y)".tar.gz backup.sql
