#!/usr/bin/env bash
# This script will display a list of currently running processes with user-oriented format and process hierarchy.

# Display the header
#printf "%-10s %-5s %-5s %-6s %-6s %-8s %-4s %-8s %-9s %s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "COMMAND"

# Display the process information using ps command
#ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | sed 's/$/ /' | awk '{printf("%-10s %-5s %-5s %-6s %-6s %-8s %-4s %-8s %-9s %s",$1,$2,$3,$4,$5,$6,$7,$8,$9,$10); for (i=11; i<=NF; i++) printf("%s ", $i); printf("\n")}' | head -50
ps faux
