#!/usr/bin/env bash
# This script tells the story of /etc/passwd using the while loop + IFS.

# Reading the /etc/passwd file line by line using a while loop
while IFS=: read -r username _ uid gid info home shell; do
    # Extracting the user ID's place and passcode
    passcode=$(echo "$info" | cut -d' ' -f1)
    gang=$(echo "$info" | cut -d' ' -f2)

    # Displaying the story in the specified format
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $info"
done < /etc/passwd
