#!/usr/bin/env bash
# Script that configures and runs `nginx` as the nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/\<80\>/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill -9 apache2 # apache2 runs on port 8080 by default on the server
sudo -u nginx service nginx restart
